[package]
name = "st7789"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"
embedded-graphics-core = "0.4"
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", branch = "main", features = ["defmt"] }