[package]
name = "st7789"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal-async = "1.0.0"
embedded-hal = "1.0.0"
embedded-graphics-core = "0.4"
embassy-time = { version = "0.3.2", features = ["defmt"] }